### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by amyadzuki** [Fjolnir-Dvorak/environ#1]
The file "config_xdg.go" is badly broken.  It looks like a half-finished update was in-progress.  Please fix this because I want to use it! ^_^  I might make a PR to fix a few of the bugs later if I remember.  Take care

**Comment by Fjolnir-Dvorak** [comment]
Thank you for the bug report. I will look into it.

**Comment by Fjolnir-Dvorak** [comment]
got finally a linux back on to test and it seems to work. Still need to write tests. I will open that in a new issue
